In [1]:
import h5py as h5;
import numpy as np;
import matplotlib.pyplot as plt;

In [27]:
filedir = '/home/suerfu/nidaq/'
filename = 'Select.h5'
file = h5.File( filedir+filename, 'r' )
print( file.keys() )

<KeysViewHDF5 ['Matrix in file']>


In [28]:
matrix = file['Matrix in file']
npmatrix = np.array(matrix)
#print( matrix[:,0] )
#print( matrix[:,1] )
print( npmatrix)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]]


In [24]:
file.close()